from typing import List, Optional
from pydantic import BaseModel

class DependentRepositoryInfo(BaseModel):
    full_name: str
    description: Optional[str]
    fork: bool
    created_at: str
    updated_at: str
    pushed_at: str
    homepage: Optional[str]
    size: int
    stargazers_count: int
    language: Optional[str]
    has_issues: bool
    has_wiki: bool
    has_pages: bool
    forks_count: int
    mirror_url: Optional[str]
    open_issues_count: int
    default_branch: str
    subscribers_count: int
    uuid: str
    source_name: Optional[str]
    license: Optional[str]
    private: bool
    contributions_count: int
    has_readme: Optional[str]
    has_changelog: Optional[str]
    has_contributing: Optional[str]
    has_license: Optional[str]
    has_coc: Optional[str]
    has_threat_model: Optional[str]
    has_audit: Optional[str]
    status: Optional[str]
    last_synced_at: Optional[str]
    rank: int
    host_type: Optional[str]
    host_domain: Optional[str]
    name: str
    scm: Optional[str]
    fork_policy: Optional[str]
    github_id: Optional[str]
    pull_requests_enabled: Optional[bool]
    logo_url: Optional[str]
    github_contributions_count: Optional[int]
    keywords: List[str]
    code_of_conduct_url: Optional[str]
    contribution_guidelines_url: Optional[str]
    funding_urls: List[str]
    security_policy_url: Optional[str]